# Generated by Django 5.2.1 on 2025-05-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ubication', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(help_text='Tamaño de la colonia (número de animales)')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonies', to='colony.zone')),
            ],
        ),
    ]
