# Generated by Django 5.2.1 on 2025-05-25
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0002_colony'),
        ('users', '0003_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ])),
                ('frequency', models.IntegerField(default=3, help_text='Ratio indicating that a volunteer goes to a colony on a specific day')),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='colony.colony')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('colony', 'day'), ('volunteer', 'day')},
            },
        ),
    ]
