# Generated by Django 5.2 on 2025-05-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rol',
            new_name='role',
        ),
    ]
